### ISSUE TITLE
Spell rank not showing

### ISSUE THREAD

**Issue by Zwyk** [shoestare/eCastingBar-Classic#4]
Spell rank doesn't seem to be being displayed anywhere when checking the option to.

**Comment by shoestare** [comment]
@Zwyk Blizzard removed the function of specifying spell ranks in the combat event log in the Classic API, so this may not be able to be fixed at launch, but we'll see. I'd try to approach the problem in BFA but retail doesn't have spell ranks. The option may have to be removed altogether from the config panel, especially if the combat event log API removed spell rank recognition completely, but I'm hoping there might be some sort of workaround. I'll try to fix it at launch though.
