### ISSUE TITLE
"Hide Outline" checkbox in settings doesn't correctly load saved value

### ISSUE THREAD

**Issue by Zwyk** [shoestare/eCastingBar-Classic#5]
"Hide Outline" button in both Casting Bar and Mirror Bar always loads itself to unchecked (you have to check in then uncheck it for the Outline to show if you had it saved to be hidden before reload).

**Comment by stampis** [comment]
Same issue with "Hide Border" setting.

**Comment by shoestare** [comment]
@Zwyk @stampis Yeah I'm aware of this issue. The checkbox functionality is old code that needs to be updated. I might use an Ace3 library to fix this problem, but some rewrites are gonna be necessary. I'll keep this issue inquiry open however until it gets fixed.

**Comment by Zwyk** [comment]
Kinda related (maybe not?), but it seems like using a channeled spell sets Hirde Border to false (it shows the Border and keeps it shown afterwards).
